[package]
name = "play"
version = "0.1.0"
authors = ["Argrath67 <57122004+Argrath67@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
